# Generated by Django 3.1 on 2021-03-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='电话'),
            preserve_default=False,
        ),
    ]
