# Generated by Django 3.1 on 2021-03-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_company_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planstatus',
            old_name='status',
            new_name='title',
        ),
    ]
