# Generated by Django 3.1 on 2021-03-13 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210313_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='boat_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.boatstatus', verbose_name='船舶状态'),
        ),
        migrations.AlterField(
            model_name='planstatus',
            name='title',
            field=models.CharField(max_length=32, verbose_name='计划'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='boat_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.boatstatus', verbose_name='船舶状态'),
        ),
    ]
