# Generated by Django 3.1 on 2021-03-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210313_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.location', verbose_name='船厂/码头'),
        ),
    ]
